# Generated by Django 4.1.4 on 2023-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='demand', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
                ('graph_left', models.ImageField(default=None, upload_to='demand', verbose_name='График №2')),
                ('graph_right', models.ImageField(default=None, upload_to='demand', verbose_name='График №1')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='geography', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Заголовок')),
                ('table', models.TextField(default=None, verbose_name='Таблица')),
                ('graph', models.ImageField(default=None, upload_to='geography', verbose_name='График')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='homepage', max_length=100, verbose_name='Заголовок')),
                ('text_1', models.TextField(default=None, verbose_name='Текст 1')),
                ('text_2', models.TextField(default=None, verbose_name='Текст 2')),
                ('image_1', models.ImageField(default=None, upload_to='home', verbose_name='img 1')),
                ('image_2', models.ImageField(default=None, upload_to='home', verbose_name='img 2')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='skills', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
            ],
        ),
    ]
